image: nixos/unstable

packages:
  - nixos.cachix

environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"

secrets:
  - f2907d38-97b4-4e7d-9fb9-57b3fb0135af

tasks:
- setup_cachix: |
    cachix authtoken --stdin < ~/.cachix_token
    cachix use misterio
- build: |
    cd nix-config
    cachix watch-exec misterio nix build .#{pmis,alacritty-ligatures,comma,photoprism}
