keys:
  # Users
  - &users:
    - &misterio 7088C7421873E0DB97FF17C2245CAB70B4C225E9
  # Hosts
  - &hosts:
    - &atlas age1hm5lf4qk84r4wh00atn6hpts7mpdx80adq26wht2e5qh9ewvhyaszfv82d
    - &merope age1709qfrwglm75v5x8lpuhryt83k6p6c90npplzzec6a5w8ct93ejscpqpc3
    - &alcyone age1uxvuygmvwpfjrd9d3ulg6ln8dgvaw4l2c90mw0tr72qg3n8vd9ns3dm000
    - &celaeno age1gxhy9eq38xfplay0kvkeyvsg96g0c4p6rkhajkrj8nc9dswdzqhssgvns0
    - &taygeta age1szxq4pz3wuxrs5ynqt3gys4wxslg27lr67smsqvg5guhap800szs3y73vd
    - &maia age150kp4hx4qzfpcxayyfh8xcv8nf0uudppsknwgzgj724djqup2qvqz2gwj5
    - &pleione age1rse7ehe8dju0yakqarmlnqdjdgaflv7rszznfaq9my7zdpemuqgshsyu8k
creation_rules:
  - path_regex: hosts/taygeta/secrets.ya?ml$
    key_groups:
    - age:
      - *taygeta
      pgp:
      - *misterio
  - path_regex: hosts/celaeno/secrets.ya?ml$
    key_groups:
    - age:
      - *celaeno
      pgp:
      - *misterio
  - path_regex: hosts/alcyone/secrets.ya?ml$
    key_groups:
    - age:
      - *alcyone
      pgp:
      - *misterio
  - path_regex: hosts/merope/secrets.ya?ml$
    key_groups:
    - age:
      - *merope
      pgp:
      - *misterio

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *atlas
      - *merope
      - *alcyone
      - *celaeno
      - *taygeta
      - *maia
      - *pleione
      pgp:
      - *misterio
