#!/usr/bin/env bash
if [[ "$(~/bin/darkmode query)" == "dark" ]]; then
    echo 'scheme = "dark"' > ~/.config/qutebrowser/scheme.py
else
    echo 'scheme = "light"' > ~/.config/qutebrowser/scheme.py
fi

socket="${XDG_RUNTIME_DIR}/qutebrowser/ipc-$(echo -n "$USER" | md5sum | cut -d' ' -f1)"
if [ -S $socket ]; then
    printf '{"args": [":config-source"], "target_arg": null, "protocol_version": 1}\n' | socat - UNIX-CONNECT:$socket
fi
