#!/usr/bin/env python3
 
# Generated by opencode (using deepseek-v4-pro)
# Don't judge me too much, the code is horrendous, but works.
 
"""Hierarchical budget/category expense matrix from Firefly III API.

Pulls budgets and transactions, then prints a hierarchical table with budgets
as super-rows and categories nested underneath. Budget rows show spent/budgeted
with manual-limits-first, auto_budget fallback. The Avg/mo and total column
(shown with 2+ complete months) excludes the last month only when it is the
current (partial) month, to avoid skewing the average. Partial-month columns are
marked with *.

Usage:
    ./expenses.py [start_month] [end_month]

Set FIREFLY_BASE and FIREFLY_TOKEN_PATH env vars to configure.
"""

import calendar
import json
import os
import sys
import urllib.request
from collections import OrderedDict
from datetime import datetime

BASE = os.environ.get("FIREFLY_BASE", "https://firefly.m7.rs")
TOKEN_PATH = os.environ.get("FIREFLY_TOKEN_PATH", "/run/secrets/firefly-pat")
COL_W = 12
TOT_W = 7
MONTH_ABBR = [
    "", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
]
BOLD = "\033[1m"
RED = "\033[31m"
GREEN = "\033[32m"
RESET = "\033[0m"


# ── color helpers ────────────────────────────────────────────────────────────

def _style(text: str, bold: bool = False, italic: bool = False) -> str:
    """Apply ANSI bold and/or italic to text."""
    if bold and italic:
        return f"\033[3;1m{text}\033[0m"
    elif italic:
        return f"\033[3m{text}\033[0m"
    elif bold:
        return f"\033[1m{text}\033[0m"
    return text


def _red(s: str, bold: bool = False, italic: bool = False) -> str:
    prefix = "3;" if italic else ""
    b = f"{prefix}1;" if bold else prefix
    return f"\033[{b}31m{s}\033[0m"


def _green(s: str, bold: bool = False, italic: bool = False) -> str:
    prefix = "3;" if italic else ""
    b = f"{prefix}1;" if bold else prefix
    return f"\033[{b}32m{s}\033[0m"


def _bold_label(text: str, width: int) -> str:
    """Bold a label and right-pad to width (ANSI-safe)."""
    return f"\033[1m{text}\033[0m{' ' * (width - len(text))}"


# ── api ──────────────────────────────────────────────────────────────────────

def _api(token: str, path: str) -> list[dict]:
    """GET a paginated Firefly III endpoint, returning all data items."""
    url = f"{BASE}/api/v1/{path}"
    items = []
    page = 1
    while True:
        sep = "&" if "?" in url else "?"
        req = urllib.request.Request(f"{url}{sep}page={page}")
        req.add_header("Authorization", f"Bearer {token}")
        req.add_header("Accept", "application/json")
        with urllib.request.urlopen(req) as resp:
            body = json.loads(resp.read().decode())
        items.extend(body["data"])
        total = body.get("meta", {}).get("pagination", {}).get("total_pages", 1)
        if page >= total:
            break
        page += 1
    return items


def _months_in_range(start: str, end: str) -> int:
    sy, sm = int(start[:4]), int(start[5:7])
    ey, em = int(end[:4]), int(end[5:7])
    return (ey - sy) * 12 + (em - sm) + 1


# ── formatting ───────────────────────────────────────────────────────────────

def _month_label(ym: str) -> str:
    y, m = ym.split("-")
    return f"{MONTH_ABBR[int(m)]}{y[2:]}"


def _fmt_cell(value: float, sign: str = "", force_sign: bool = False,
              bold: bool = False, width: int = COL_W, italic: bool = False) -> str:
    """Format a single cell value, optionally with a forced sign and colour."""
    if abs(value) < 0.005:
        return _style("-".rjust(width), bold, italic)
    if force_sign:
        s = "+" if value >= 0 else "-"
        color = (_green if value >= 0 else _red)
    elif sign:
        s = sign
        color = (_red if sign == "-" else _green)
    else:
        return _style(f"{value:>{width}.0f}", bold, italic)
    return color(f"{s}{abs(value):.0f}".rjust(width), bold=bold, italic=italic)


def _fmt_budget_cell(spent: float, limit: float | None = None,
                     bold: bool = False, width: int = COL_W,
                     italic: bool = False) -> str:
    """Budget row cell: spent/budgeted when limit is available, coloured by status."""
    has_limit = limit is not None and limit > 0
    zero_spent = abs(spent) < 0.005
    if not has_limit:
        if zero_spent:
            return _style("-".rjust(width), bold, italic)
        return _fmt_cell(spent, bold=bold, width=width, italic=italic)
    overspent = abs(spent) > limit
    s = f"{spent:.0f}/{limit:.0f}"
    return (_red if overspent else _green)(s.rjust(width), bold=bold, italic=italic)


def _avg(values: dict[str, float], n: int) -> float:
    return sum(values.values()) / n


def _print_table(budgets: OrderedDict, revenue: dict[str, float],
                 months: list[str], budget_order: list[str],
                 limits: dict[str, dict[str, float]]) -> None:
    """Print the full hierarchical budget/category expense matrix."""
    n = len(months)
    labels = [_month_label(m) for m in months]
    now = datetime.now()
    current_ym = f"{now.year}-{now.month:02d}"
    if months and months[-1] == current_ym:
        labels[-1] += "*"
        completed = months[:-1]
        partial_month = months[-1]
    else:
        completed = months
        partial_month = None
    show_total = len(completed) > 1
    show_avg = len(completed) > 1
    label_w = max(26, max((len(b) for b in budgets), default=0) + 2)

    def _avg_col(values: dict[str, float]) -> float:
        if not show_avg:
            return 0
        return sum(values[m] for m in completed) / len(completed)

    def _total_col(values: dict[str, float]) -> float:
        if not show_total:
            return 0
        return sum(values[m] for m in completed)

    # header
    cols = n + (1 if show_total else 0) + (1 if show_avg else 0)
    month_headers = []
    for i, lbl in enumerate(labels):
        if partial_month and i == n - 1:
            month_headers.append(f"\033[3m{' ' * (COL_W - len(lbl))}{lbl}\033[0m")
        else:
            month_headers.append(f"{lbl:>{COL_W}}")
    header = f"{'Budget / Category':<{label_w}}" + "".join(month_headers)
    if show_total:
        header += f" │{'Total':>{TOT_W}}"
    if show_avg:
        header += f"  {'Avg/mo':>{TOT_W}}"

    right_width = 0
    if show_total:
        right_width += 2 + TOT_W
    if show_avg:
        right_width += 2 + TOT_W
    sep_left = "─" * (label_w + COL_W * n + (1 if show_total else 0))
    if show_total:
        sep = sep_left + "┼" + "─" * (right_width - 2)
    else:
        sep = sep_left + "─" * right_width
    print(header)
    print(sep)

    # order budgets by API list, then alphabetically for unknown ones
    ordered = [b for b in budget_order if b in budgets]
    seen = set(ordered)
    ordered += sorted(b for b in budgets if b not in seen)

    for bname in ordered:
        cats = budgets[bname]
        sorted_cats = sorted(cats.items(),
                             key=lambda kv: _avg(kv[1], n), reverse=True)
        bt = {m: sum(c[m] for c in cats.values()) for m in months}
        budget_limits = limits.get(bname, {})
        cells = "".join(_fmt_budget_cell(bt[m], budget_limits.get(m), bold=True, italic=(m == partial_month)) for m in months)
        line = f"{_bold_label(bname, label_w)}{cells}"
        if show_total:
            line += f" │{_fmt_cell(_total_col(bt), bold=True, width=TOT_W)}"
        if show_avg:
            line += f"  {_fmt_cell(_avg_col(bt), bold=True, width=TOT_W)}"
        print(line)

        for cname, mdata in sorted_cats:
            cells = "".join(_fmt_cell(mdata[m], italic=(m == partial_month)) for m in months)
            line = f"  {cname:<{label_w - 2}}{cells}"
            if show_total:
                line += f" │{_fmt_cell(_total_col(mdata), width=TOT_W)}"
            if show_avg:
                line += f"  {_fmt_cell(_avg_col(mdata), width=TOT_W)}"
            print(line)

    # expense totals
    expense_totals = {m: 0.0 for m in months}
    for bname in ordered:
        for m in months:
            expense_totals[m] += sum(c[m] for c in budgets[bname].values())

    print(sep)
    cells = "".join(_fmt_cell(expense_totals[m], sign="-", bold=True, italic=(m == partial_month)) for m in months)
    line = f"{_bold_label('TOTAL EXPENSES', label_w)}{cells}"
    if show_total:
        line += f" │{_fmt_cell(_total_col(expense_totals), sign='-', bold=True, width=TOT_W)}"
    if show_avg:
        line += f"  {_fmt_cell(_avg_col(expense_totals), sign='-', bold=True, width=TOT_W)}"
    print(line)

    rev = {m: revenue.get(m, 0.0) for m in months}
    cells = "".join(_fmt_cell(rev[m], sign="+", bold=True, italic=(m == partial_month)) for m in months)
    line = f"{_bold_label('REVENUE', label_w)}{cells}"
    if show_total:
        line += f" │{_fmt_cell(_total_col(rev), sign='+', bold=True, width=TOT_W)}"
    if show_avg:
        line += f"  {_fmt_cell(_avg_col(rev), sign='+', bold=True, width=TOT_W)}"
    print(line)

    net = {m: rev[m] - expense_totals[m] for m in months}
    cells = "".join(_fmt_cell(net[m], force_sign=True, bold=True, italic=(m == partial_month)) for m in months)
    line = f"{_bold_label('NET', label_w)}{cells}"
    if show_total:
        line += f" │{_fmt_cell(_total_col(net), force_sign=True, bold=True, width=TOT_W)}"
    if show_avg:
        line += f"  {_fmt_cell(_avg_col(net), force_sign=True, bold=True, width=TOT_W)}"
    print(line)

    budgeted_totals = {m: 0.0 for m in months}
    for bname in ordered:
        for m in months:
            budgeted_totals[m] += limits.get(bname, {}).get(m, 0.0)
    cells = "".join(_fmt_cell(budgeted_totals[m], bold=True, italic=(m == partial_month)) for m in months)
    line = f"{_bold_label('BUDGETED', label_w)}{cells}"
    if show_total:
        line += f" │{_fmt_cell(_total_col(budgeted_totals), bold=True, width=TOT_W)}"
    if show_avg:
        line += f"  {_fmt_cell(_avg_col(budgeted_totals), bold=True, width=TOT_W)}"
    print(line)

    left = {m: budgeted_totals[m] - expense_totals[m] for m in months}
    cells = "".join(_fmt_cell(left[m], force_sign=True, bold=True, italic=(m == partial_month)) for m in months)
    line = f"{_bold_label('LEFT', label_w)}{cells}"
    if show_total:
        line += f" │{_fmt_cell(_total_col(left), force_sign=True, bold=True, width=TOT_W)}"
    if show_avg:
        line += f"  {_fmt_cell(_avg_col(left), force_sign=True, bold=True, width=TOT_W)}"
    print(line)


# ── data pipeline ────────────────────────────────────────────────────────────

def _parse_args() -> tuple[str, str, str, str]:
    """Return (token, start_month, end_month, end_day)."""
    try:
        with open(TOKEN_PATH) as f:
            token = f.read().strip()
    except FileNotFoundError:
        print(f"Token not found at {TOKEN_PATH}", file=sys.stderr)
        sys.exit(1)

    if len(sys.argv) > 1:
        start = sys.argv[1]
    else:
        now = datetime.now()
        start = f"{now.year}-{now.month:02d}"
    if len(sys.argv) > 2:
        end = sys.argv[2]
    else:
        now = datetime.now()
        end = f"{now.year}-{now.month:02d}"

    ey, em = int(end[:4]), int(end[5:7])
    end_day = str(calendar.monthrange(ey, em)[1])
    return token, start, end, end_day


def _fetch_transactions(token: str, start: str, end: str, end_day: str) -> tuple[list, dict, set]:
    """Pull transactions from API, expanding splits. Returns (rows, revenue, months)."""
    rows: list[tuple[str, str, str, float]] = []
    revenue: dict[str, float] = {}
    all_months: set[str] = set()

    txns = _api(token, f"transactions?start={start}-01&end={end}-{end_day}&limit=200")
    for txn in txns:
        for split in txn["attributes"]["transactions"]:
            m = split["date"][:7]
            a = float(split["amount"])
            if split["type"] == "withdrawal":
                b = split.get("budget_name")
                c = split.get("category_name")
                if b and c:
                    rows.append((b, c, m, a))
                    all_months.add(m)
            elif split["type"] == "deposit":
                revenue[m] = revenue.get(m, 0) + a
                all_months.add(m)

    return rows, revenue, all_months


def _build_cube(rows: list, months: list[str]) -> OrderedDict:
    """Pivot flat rows into budget -> category -> {month: total}."""
    budgets = OrderedDict()
    for b, c, m, a in rows:
        if m not in months:
            continue
        budgets.setdefault(b, OrderedDict()).setdefault(c, {m: 0.0 for m in months})
        budgets[b][c][m] += a
    return budgets


def _fetch_effective_limits(token: str, budget_list: list[dict],
                            start: str, end: str) -> dict[str, dict[str, float]]:
    """Return {budget_name: {month: effective_cap}}.

    Uses manual budget limits when available, falling back to auto_budget_amount.
    """
    # index budgets by id
    budget_map: dict[str, dict] = {}
    for b in budget_list:
        budget_map[b["id"]] = b["attributes"]

    # fetch all manual limits for the range
    ey, em = int(end[:4]), int(end[5:7])
    last_day = calendar.monthrange(ey, em)[1]
    limits_raw = _api(token, f"budget-limits?start={start}-01&end={end}-{last_day:02d}&limit=200")

    # group manual limits: budget_id -> {month: amount}
    manual: dict[str, dict[str, float]] = {}
    for lim in limits_raw:
        bid = str(lim["attributes"]["budget_id"])
        month = lim["attributes"]["start"][:7]
        manual.setdefault(bid, {})[month] = float(lim["attributes"]["amount"])

    # generate all months in range
    sy, sm = int(start[:4]), int(start[5:7])
    ey, em = int(end[:4]), int(end[5:7])
    all_months: list[str] = []
    y, m = sy, sm
    while (y, m) <= (ey, em):
        all_months.append(f"{y}-{m:02d}")
        m += 1
        if m > 12:
            m = 1
            y += 1

    result: dict[str, dict[str, float]] = {}
    for bid, attrs in budget_map.items():
        name = attrs["name"]
        manual_for_bid = manual.get(bid, {})
        auto = attrs.get("auto_budget_amount")
        auto_amount = float(auto) if auto else None

        result[name] = {}
        for month in all_months:
            if month in manual_for_bid:
                result[name][month] = manual_for_bid[month]
            elif auto_amount is not None:
                result[name][month] = auto_amount

    return result


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    token, start, end, end_day = _parse_args()

    budget_list = _api(token, "budgets")
    budget_order = [b["attributes"]["name"] for b in budget_list]

    rows, revenue, all_months = _fetch_transactions(token, start, end, end_day)

    months = sorted(m for m in all_months if start <= m <= end)
    if not months:
        print("No data found.", file=sys.stderr)
        sys.exit(1)

    budgets = _build_cube(rows, months)
    limits = _fetch_effective_limits(token, budget_list, start, end)

    # Include budgets that have limits but no spending in the range
    for bname, month_limits in limits.items():
        if bname not in budgets and month_limits:
            budgets[bname] = OrderedDict()

    _print_table(budgets, revenue, months, budget_order, limits)


if __name__ == "__main__":
    main()
