# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" "amdgpu" ];
  boot.initrd.luks.devices."nixenc".device =
    "/dev/disk/by-uuid/320599e3-21f9-465e-a2f2-d078eccc34c0";
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=4G" "mode=755" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/28E4-87AC";
      fsType = "vfat";
    };

    "/data/games" = {
      device = "/dev/disk/by-uuid/53b00f4f-1dee-4aae-bc96-3982f2b04c90";
      fsType = "btrfs";
      options = [ "subvol=data/games" "compress=zstd" ];
    };

    "/data/home" = {
      device = "/dev/disk/by-uuid/53b00f4f-1dee-4aae-bc96-3982f2b04c90";
      fsType = "btrfs";
      options = [ "subvol=data/home" "compress=zstd" ];
    };

    "/data/srv" = {
      device = "/dev/disk/by-uuid/53b00f4f-1dee-4aae-bc96-3982f2b04c90";
      fsType = "btrfs";
      options = [ "subvol=data/srv" "compress=zstd" ];
    };

    "/data/var" = {
      device = "/dev/disk/by-uuid/53b00f4f-1dee-4aae-bc96-3982f2b04c90";
      fsType = "btrfs";
      options = [ "subvol=data/var" "compress=zstd" ];
    };

    "/dotfiles" = {
      device = "/dev/disk/by-uuid/53b00f4f-1dee-4aae-bc96-3982f2b04c90";
      fsType = "btrfs";
      options = [ "subvol=dotfiles" "compress=zstd" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/53b00f4f-1dee-4aae-bc96-3982f2b04c90";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "compress=zstd" ];
    };
  };

  swapDevices = [ ];

}
