# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."nixenc".device = "/dev/disk/by-uuid/32d93839-2606-4472-a4ba-01b8510937bb";

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
      options = [ "defaults" "size=4G" "mode=755" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/96C2-490B";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9ded8eaf-5411-425b-9664-1208aadd11b9";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/9ded8eaf-5411-425b-9664-1208aadd11b9";
      fsType = "btrfs";
      options = [ "subvol=data" "compress=zstd" ];
    };

  fileSystems."/dotfiles" =
    { device = "/dev/disk/by-uuid/9ded8eaf-5411-425b-9664-1208aadd11b9";
      fsType = "btrfs";
      options = [ "subvol=dotfiles" "compress=zstd" ];
    };

  swapDevices = [ ];
}
