#!/usr/bin/env bash
if [[ -z "$1" ]]; then
    setplayer="$(cat /run/user/$UID/currentplayer 2> /dev/null)"
    players=$(mpris-ctl list | grep "$setplayer") && \
    echo "$players" | head -1
else
    echo "$1" > /run/user/$UID/currentplayer
fi
