#!/usr/bin/env bash

# Query
if [[ $* == *-Q* ]]; then
    basename $(cat ~/.bg)
    exit
fi

# List
if [[ $* == *-L* ]]; then
    ls -1R ~/Pictures/Wallpapers/ | grep -E ".png|.jpg|.jpeg"
    exit
fi

# Random
if [[ $* == *-R* ]]; then
    wallpaper=$(~/bin/setwallpaper -L | shuf -n 1)
# Specified
else
    wallpaper=$1
fi

# From scheme
if [[ $* == *-S* ]]; then
    inkscape --export-type="png" \
    ~/.nix-wallpaper.svg -w 2560 -h 1080 -o \
    $HOME/Pictures/Wallpapers/nix-wallpaper.png
    wallpaper="nix-wallpaper.png"
fi

wallpaper=~/Pictures/Wallpapers/"${wallpaper}"

echo "${wallpaper}" > ~/.bg
pgrep -x sway &>/dev/null && swaybg.sh &>/dev/null & \

if [[ $(flavours current 2>/dev/null) == "generated" ]]; then
    flavours generate $(darkmode query) "${wallpaper}" --stdout | flavours apply --stdin
fi
